server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/stats
    username: user
    password: password

logging.level.org:
  springframework:
    orm:
      jpa: INFO
    transaction: INFO
    transaction.interceptor: TRACE
    orm.jpa.JpaTransactionManager: DEBUG
  hibernate:
    SQL: DEBUG
    type: TRACE
    orm.jdbc.bind: TRACE